### ISSUE TITLE
xslDirectories in plugin configuration doesn't work

### ISSUE THREAD

**Issue by arkamy** [cmarchand/xslDoc-maven-plugin#1]
Use of xslDirectories in plugin configuration doesn't work.
I think that maven passes a List<String> and not a List<File> like declared in XslDocMojo class.
Following exception is raised :

_[INFO] Generating "XSL Doc" report.
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] java.lang.String cannot be cast to java.io.File
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.ClassCastException: java.lang.String cannot be cast to java.io.File
	at top.marchand.xml.maven.xslDoc.XslDocMojo.generateGauloisConfig(XslDocMojo.java:236)
	at top.marchand.xml.maven.xslDoc.XslDocMojo.generate(XslDocMojo.java:87)_

**Comment by cmarchand** [comment]
Attach your pom, please, and explain the environment you use.
But I think you may be right under windows...

**Comment by cmarchand** [comment]
Configuration has totally changed. See Wiki
